### ISSUE TITLE
Metadata needs for MAXL and fc2ago.py layer items in AGO

### ISSUE THREAD

**Issue by mhoole** [bcgov/whse_2_agol#11]
https://proj.data.gov.bc.ca/jira/browse/MAP-1482

From: Hoole, Meg CITZ:EX
Sent: October 5, 2020 5:17 PM
To: 'Brock Anderson' <brock@bandersgeo.ca>
Cc: Boulstridge, Marion CITZ:EX <Marion.Boulstridge@gov.bc.ca>; Tonkin, Bruce CITZ:EX <Bruce.Tonkin@gov.bc.ca>
Subject: Metadata needs for MAXL and fc2ago.py layer items in AGO

 

 

Hi Brock

 

There are a couple more asks for metadata changes that may not have crossed your path yet:

 

For the map image layer items - a  'Change Notice' that speaks to the replacement of the dynamic json service urls – it can now be removed... see https://governmentofbc.maps.arcgis.com/home/item.html?id=1923f13a74974ea48a6fdc56630703ba
If possible, can we add a note to the top of the Description section of map image layer items that drives the users to the corresponding feature layer items instead?
Something like:
NOTICE: This item will be deprecated in “the future” (we don’t have a date yet – but we can discuss).   We recommend you use the feature layer item instead – see “link to feature layer item”
The AGO hosted layers replicated by the fc2ago.py script do not currently have the metadata automated like the MAXL does.  Can we do the same metadata updates via script for these layers that we currently do for the MAXL layers?  See for an example layer:  https://governmentofbc.maps.arcgis.com/home/item.html?id=eacb5780fce3411791278b2fa31d6f07
 

Thank you

 

___________________________________________________________________________________

Meg Hoole  __  | Data Administrator | DataBC | Data Systems and Services Branch | Digital Platforms and Data Division

Office of the Chief Information Officer – Ministry of Citizens’ Services

**Comment by banders** [comment]
To confirm:

The following two tasks mentioned by @mhoole above relate to the "AGO Publish" process which publishes AGO items as "Map Image Layers" that refer to AGS layers
- Remove the "change notice" from item descriptions
- Add link to the corresponding feature layer

The following task relates to the fc2ago.py script which publishes "Feature Layers" hosted by Esri:
- Add additional metadata (description, etc), similar to the metadata in items published by "AGO Publish"

Note: The AGO Publish process is in the midst of being replaced.  The existing (old) version is kept in this repository:
- https://gogs.data.gov.bc.ca/waops/ago_publish
The new (in development) version is kept in this repository:
- https://gogs.data.gov.bc.ca/waops/whse_2_agol/app/ago

**Comment by banders** [comment]
@bruce-tonkin @mhoole @mboulstr1 Regarding the link from the Map Image layer to the corresponding Feature Layer: I'm considering how the "AGO publish" script should determine which Feature Layer corresponds to each Map Image layer.  Are these relationships recorded anywhere currently?  

We're getting into the territory of inter-app communication.  Both "MXD Publish" and "AGO Publish" need some information produced by fc2ago.py.  We could re-imagine fc2ago.py as a microservice which has its own API that allows other apps to query a list of the feature classes and AGO items it manages.  Alternatively, we can take a smaller step and just extend fc2ago.py save a file that specifies the feature classes it publishes to AGO and the corresponding AGO items.  The file would be placed in a location that is accessible to "MXD Publish" and "AGO Publish" so they could do both of the following

1. Exclude the fc2ago feature classes from the .mxd files and map services
2. Add a link from AGO Map Image layers to the corresponding Feature Layer

(Note: The "MXD Publish" process already uses an exclusion file that allows us to achieve item 1, but that file must be maintained independently from fc2ago.py, and that file doesn't allow us to achieve item 2.  The approach suggested above would either supersede the existing exclusion list file, or would be used in addition to it.)

There may need tp be some access restrictions on the information published by fc2ago, and that would constrain our approach.

Thoughts on how we should proceed?

**Comment by mhoole** [comment]
This is not recorded anywhere that I’m aware of….

It could be possible to create a list of the existing feature layer and map image layer MAXL items that could be referenced by the script?

The titles and the service URLs of the feature layer and map image layers should match…. And might be suitable for matching?

Cheers, Meg

**Comment by banders** [comment]
Certainly it is possible to create a list of relationships between feature layers and the corresponding map image layers.  That's is exactly what we need.  The challenge is to create a list which is reliable, ideally without significant effort.

Such a list could be created manually (by a human) and updated if the relationships change, but that could be brittle.  

Alternatively, it may be possible to have those relationships automatically detected, but there are challenges with that too.  I don't think it's possible to match on the service URLs because there is no common information in the URLs.  It may be possible to match on service titles, but I suspect we'll find that to be brittle.  Ideally we could match on feature class because "AGO Publish" treats feature class as a unique key for the Map Image Layer items it manages.  The trouble is that, currently, fc2ago.py doesn't have any way of sharing the items it manages and their corresponding feature classes.  

I suspect our best option is to extend fc2ago such that it can share a list of the items it manages and their corresponding feature classes.  "MXD Publish" would then access that list to match map image layer items to feature layer items.  How exactly fc2ago shares the list is a key detail to be determined.

**Comment by bruce-tonkin** [comment]
@banders   I will setup a meeting to talk further.

**Comment by banders** [comment]
Thanks everyone for the call yesterday to discuss this issue.  One thing that didn't come up yesterday, but which I think I now understand is:

_In the future, "AGO publish" won't publish feature classes that have corresponding items published by "fc2ago" (because those feature classes will be in the exclusion list).  The ~17 Map Image Layers that have corresponding Feature Layers will cease to exist soon.  Any links that we create from the Map Image Layers to the corresponding Features will be only temporary._  

Are these statements correct?

If so, perhaps we should address the requirement for the links outside the context of any changes to "AGO publish" or "fc2ago".  Instead, we might consider creating a one-time-use script that just adds the links by updating the ~17 relevant AGO items.

Thoughts?

**Comment by bruce-tonkin** [comment]
@banders  Brock, I believe your first statement is accurate.  We will not duplicate the existing Feature Layers.
I am however not clear on your second paragraph.
I was however talking with @mhoole this morning.  Meg will be doing some testing with Ago Items where the url for the item changes. We need to confirm that ago applications built off an Ago Item, will still point to the same underlying data, if the URL (or link to the underlying mini-maxl item) changes.  The current way of publishing items in ArcMap may result in a different layer ID's, however if you are tracking all items using the common Catalog Name like "Meteorological Monitoring Sites", then we may be fine.  So, no response required just yet, but once Meg has finished her testing, I will setup another meeting to talk further.

**Comment by banders** [comment]
@bruce-tonkin You mentioned that my suggestion above was unclear. I'll try again:  I meant to suggest that we could create _a new script_ to add links from the ~17 Map Image Layer items to the corresponding Feature Layer items.  We would probably only run the script one time... it wouldn't need to be configured as a scheduled process.

I suggested this approach because it seems unhelpful to extend "AGO Publish" to create the links when we expect the ~17 Map Image Layer items will soon be excluded from "AGO Publish" anyway.

**Comment by mboulstr1** [comment]
This is off the table at the moment.  We can do this work manually and add the layers to the exclusion list.
